GET http://localhost:9001/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJvbGNheUBnbWFpbC5jb20iLCJkaXNwbGF5TmFtZSI6Ik9sY2F5IFVzdGEiLCJwaWN0dXJlIjoiaHR0cHM6Ly9pLnBpbmltZy5jb20vNTY0eC9mNC9jMi9mZS9mNGMyZmUwZjIzZGMwNjJhMGU3ZGIyN2U3YTVhZGZlNC5qcGciLCJzdWIiOiIzIiwiaWF0IjoxNjQ1NjE4NzY5fQ.L2yctYi8H4wJhw26sh9aaadeT-SAux2rzSNOJKCcEig

